### ISSUE TITLE
Can't run with Terraform Cloud with prefix mode

### ISSUE THREAD

**Issue by alex-3sr** [infracost/infracost#943]
Hi All,

I'm trying since this morning to start working infracost in Azure DevOps PR by using Terraform Cloud.
I encounter 2 difficulties during this configuration.

First, even by set **INFRACOST_TERRAFORM_CLOUD_TOKEN** with the correct token, it always need a **.terraformrc** file
```
Running infracost breakdown using:
  $ infracost breakdown --no-color --format json --path /home/vsts/work/1/s/Terraform
time="2021-09-06T16:27:34Z" level=info msg="Detected Terraform directory at /home/vsts/work/1/s/Terraform"
time="2021-09-06T16:27:34Z" level=debug msg="Checking if /home/vsts/work/1/s/Terraform is a git repo"
time="2021-09-06T16:27:34Z" level=debug msg="Creating temporary config file for Terraform credentials"
time="2021-09-06T16:27:34Z" level=debug msg="TF_CLI_CONFIG_FILE is set, copying existing config from .terraformrc to config to temporary config file /tmp/824491119"
Error: open /home/vsts/work/1/s/Terraform/.terraformrc: no such file or directory
##[error]Bash exited with code '1'.
```

The workaround is to set a task before for write a .terraformrc file like for example 
```yaml
- bash: |
    cat << EOF >> .terraformrc
    credentials "app.terraform.io" {
      token = "$(tf_token)"
    }
    EOF
  displayName: Write Terraform.rc file
  workingDirectory: $(System.DefaultWorkingDirectory)/$(tf_path)
```

I think that using **INFRACOST_TERRAFORM_CLOUD_TOKEN**, it could be enough and able to write .terraformrc if needed really, no  ?

BTW, now that I can go on and have a workaround, it seem that it doesn't like my backend configuration and got this error ->
```
Running infracost breakdown using:
  $ infracost breakdown --no-color --format json --path /home/vsts/work/1/s/Terraform
time="2021-09-06T16:39:21Z" level=info msg="Detected Terraform directory at /home/vsts/work/1/s/Terraform"
time="2021-09-06T16:39:21Z" level=debug msg="Checking if /home/vsts/work/1/s/Terraform is a git repo"
time="2021-09-06T16:39:21Z" level=debug msg="Creating temporary config file for Terraform credentials"
time="2021-09-06T16:39:21Z" level=debug msg="TF_CLI_CONFIG_FILE is set, copying existing config from .terraformrc to config to temporary config file /tmp/034790990"
time="2021-09-06T16:39:21Z" level=debug msg="Writing Terraform credentials to temporary config file /tmp/034790990"
time="2021-09-06T16:39:21Z" level=info msg="starting: Running terraform plan"
time="2021-09-06T16:39:21Z" level=info msg="Running command: /usr/bin/terraform plan -input=false -lock=false -no-color -out=/tmp/tfplan442482005"
time="2021-09-06T16:39:23Z" level=debug binary=terraform
time="2021-09-06T16:39:23Z" level=debug binary=terraform msg="Error: error starting operation: The configured \"remote\" backend encountered an unexpected error:"
time="2021-09-06T16:39:23Z" level=debug binary=terraform
time="2021-09-06T16:39:23Z" level=debug binary=terraform msg="invalid value for workspace"
time="2021-09-06T16:39:23Z" level=debug binary=terraform

  Terraform command failed with:
    Error: error starting operation: The configured "remote" backend encountered an unexpected error:
    invalid value for workspace

Error: Error running terraform plan: exit status 1
##[error]Bash exited with code '1'.
```

On my config, I tried to use **INFRACOST_TERRAFORM_WORKSPACE** with only environnement like "PROD" or full workspace name "PROJECT-PROD", in both case I've same error. My backend configuration is like this ->
```hcl
terraform {
  required_version = "~> 1.0.3"
  required_providers {
    azurerm = {
      version = "~> 2"
      source  = "hashicorp/azurerm"
    }
  }
  backend "remote" {
    hostname     = "app.terraform.io"
    organization = "ORG"
    workspaces {
      prefix = "PROJECTXX-"
    }
  }
}
```

It's like the prefix mode in workspace is not accepted, only name is accepted. Does I'm correct ?
Here my task on Azure DevOps ->
```yaml
- bash: |
    sudo apt-get update -qq && sudo apt-get -qq install bc curl git
    curl -sL https://github.com/infracost/infracost/releases/latest/download/infracost-linux-amd64.tar.gz | tar xz -C /tmp
    sudo mv /tmp/infracost-linux-amd64 /usr/bin/infracost
    curl -sL -o infracost_diff.sh https://raw.githubusercontent.com/infracost/infracost/master/scripts/ci/diff.sh
    chmod +x infracost_diff.sh
    ./infracost_diff.sh
  displayName: Run Infracost diff
  env:
    SYSTEM_ACCESSTOKEN: $(System.AccessToken)
    INFRACOST_API_KEY: <xxxxx>
    INFRACOST_TERRAFORM_BINARY: /usr/bin/terraform
    INFRACOST_TERRAFORM_WORKSPACE: PROD
    INFRACOST_TERRAFORM_CLOUD_TOKEN: $(tf_token)
    INFRACOST_LOG_LEVEL: debug
    ARM_CLIENT_SECRET: <xxxxx>
    ARM_SUBSCRIPTION_ID: <xxxxx>
    ARM_TENANT_ID: <xxxxx>
    path: $(System.DefaultWorkingDirectory)/$(tf_path)
```

Thanks and remain at your disposal
Regards
Alexandre

**Comment by aliscott** [comment]
Thanks for the detailed issue @alex-3sr 🙌 . I'll break this comment down into the two issues.

**Issue 1:** `INFRACOST_TERRAFORM_CLOUD_TOKEN` not working

Out existing logic for the `INFRACOST_TERRAFORM_CLOUD_TOKEN` is to create a temporary `.terraformrc` and write the token to that file. However, if the `TF_CLI_CONFIG_FILE` env variable is already set then we try and copy that file to a temp file and overwrite the token. From what I can tell the issue here is that the `TF_CLI_CONFIG_FILE` env variable is already set, but the path it is set to doesn't exist (`/home/vsts/work/1/s/Terraform/.terraformrc`) so we are failing to copy it.

Are you able to `echo $TF_CLI_CONFIG_FILE` to validate this? If so, do you know what is setting this variable.

One fix from our end is to just log an error if we can't copy the existing file instead of a hard failure. I think this would resolve your use-case, what do you think?

**Issue 2:** `INFRACOST_TERRAFORM_WORKSPACE` not working

I was able to reproduce this and it looks like a bug with the `INFRACOST_TERRAFORM_WORKSPACE` being overwritten. I've pushed a fix in #946 so it should be in the next release.

In the meantime one of the following should work as a workaround:
1. Set `TF_WORKSPACE: PROD` env variable
2. Add the `terraform_workspace: PROD` variable (https://github.com/infracost/infracost-azure-devops/#terraform_workspace) to your Azure DevOps env.

Let me know if this works for you.

**Comment by alex-3sr** [comment]
Hi @aliscott 

Thank for your prompt response and help about my issues.

So, about the 1st point I debug ouput the `TF_CLI_CONFIG_FILE` and very surprising to get that as response : `.terraformrc`
I've no idea who can set this env variable, but OK I've a point to start diving and will find why soon.

For the 2nd point, I did the easy way by setting all variables in once. I'm sure that I've some extra one, but at least for go on debugging and find a woarkaround at least on first time. So i did a task like this -->
```yaml
- bash: |
    sudo apt-get update -qq && sudo apt-get -qq install bc curl git
    curl -sL https://github.com/infracost/infracost/releases/latest/download/infracost-linux-amd64.tar.gz | tar xz -C /tmp
    sudo mv /tmp/infracost-linux-amd64 /usr/bin/infracost
    curl -sL -o infracost_diff.sh https://raw.githubusercontent.com/infracost/infracost/master/scripts/ci/diff.sh
    chmod +x infracost_diff.sh
    ./infracost_diff.sh
  displayName: Run Infracost diff
  env:
    SYSTEM_ACCESSTOKEN: $(System.AccessToken)
    INFRACOST_API_KEY: xxxx
    INFRACOST_TERRAFORM_BINARY: /usr/bin/terraform
    INFRACOST_TERRAFORM_WORKSPACE: $(target_env)
    TF_WORKSPACE: PROD
    terraform_workspace: PROD
    INFRACOST_TERRAFORM_CLOUD_TOKEN: $(tf_token)
    INFRACOST_LOG_LEVEL: debug
    path: $(System.DefaultWorkingDirectory)/$(tf_path)
```

And, boum that's works better now and didn't have anymore, but now I've errors about my tfvars. but it's discussed here : https://github.com/infracost/infracost/issues/20 So I think that I will found the way to add my tfvars as env variables I hope.

I'll refresh this thread later after more improved tests

Thanls again
Regards
Alex

**Comment by alex-3sr** [comment]
So, i did more test and it's definitvely works only if I set this var **terraform_workspace**
The 2 vars **INFRACOST_TERRAFORM_WORKSPACE** and **TF_WORKSPACE** seem to have no effects, it's only working if I set **terraform_workspace**

For me on this 2nd point, it's enough for implement it.
I've to still found why TF_CLI_CONFIG_FILE is already setup on 1st point.
Left me a 3rd and last point, but I don't want to pollute this thread, and I will try to find a solution by myself, else I will post a new issue. It's just that now infracost works on Azure DevOps, but I don't have new PR comments .. I will find ^^

Thanks for all
At disposal
Alex

**Comment by alikhajeh1** [comment]
@alex-3sr re point 3, are you using Azure DevOps with Azure repos or GitHub repos? hmm maybe you found the issue as I see the comment was edited?

**Comment by alex-3sr** [comment]
> @alex-3sr re point 3, are you using Azure DevOps with Azure repos or GitHub repos? hmm maybe you found the issue as I see the comment was edited?

^^ Yes, I just discover that if there are no change, there are no comment published finally :) I didn't know that.
But if talking about 3rd point about PR comments, the comments is published as already "closed" ?
![image](https://user-images.githubusercontent.com/38663389/132396538-ce722330-ce33-4242-a3bd-a49324958af8.png)

Doesn't need it to be open for wait a validation ?

**Comment by alikhajeh1** [comment]
Great! Yep, I went with status=4 in https://github.com/infracost/infracost/blob/master/scripts/ci/diff.sh#L224 (see https://docs.microsoft.com/en-us/rest/api/azure/devops/git/pull-request-threads/create?view=azure-devops-rest-5.1#commentthreadstatus) as I thought it's an FYI comment so it doesn't need to be active for an action to be taken. What do you think?

**Comment by alex-3sr** [comment]
For my point of view, we could at least to have the choice, but in my case I really need to let it open for permit people in charge of FinOps to validate the new budget based on a PR change. And the best is to have a way to check if budget is less and so permit to let it close direclty, if more with a specific percent to wait a validation. So with this percent "acceptance" we can alert project admin that the cloud budget will increase and need maybe to be reviewed. It could be too an error of a IaC develloper who set a SKU too large and create excessive $$ who is maybe not need.

I know that in Azure DevOps we can force in branch Policy to validate comments, but it need to ben open ^^
![image](https://user-images.githubusercontent.com/38663389/132397396-a8989465-8008-40f1-a7f0-ee21b445a703.png)

Do you share my think ?

**Comment by aliscott** [comment]
@alex-3sr RE Issue 1: I've pushed a fix in https://github.com/infracost/infracost/pull/949 that will log a warning instead of a hard failure if the `TF_CLI_CONFIG_FILE` does not exist. This should fix that issue for you in CI. This will be released with the other fix in v0.9.7 which we are aiming to release tomorrow.

**Comment by alikhajeh1** [comment]
@alex-3sr RE issue 3: I've [merged a PR](https://github.com/infracost/infracost/pull/950) so you should now be able to set the variable `azure_devops_comment_status: 1` in your pipeline yaml to override the default comment status to be active :)

**Comment by alex-3sr** [comment]
@aliscott : Thanks for the PR. If I remove the custom task before for write .terraformrc file, it still failed with this error ->
```
Running infracost breakdown using:
  $ infracost breakdown --no-color --format json --path /home/vsts/work/1/s/Terraform --terraform-plan-flags "-var-file=/home/vsts/work/1/s/Terraform/Env/PROD.tf-variables.tfvars" --terraform-workspace PROD
time="2021-09-08T07:36:23Z" level=info msg="Detected Terraform directory at /home/vsts/work/1/s/Terraform"
time="2021-09-08T07:36:23Z" level=debug msg="Checking if /home/vsts/work/1/s/Terraform is a git repo"
time="2021-09-08T07:36:23Z" level=debug msg="Creating temporary config file for Terraform credentials"
time="2021-09-08T07:36:23Z" level=debug msg="TF_CLI_CONFIG_FILE is set, copying existing config from .terraformrc to config to temporary config file /tmp/421555162"
Error: open /home/vsts/work/1/s/Terraform/.terraformrc: no such file or directory
```

Ps : I think that 0.9.7 is not yet release maybe, taht's why it's not yet working for now

@alikhajeh1 : It's perfect, now PR comments are in active sate and waiting an action when I set `azure_devops_comment_status: 1`

Thanks to both,
Regards
Alexandre

**Comment by aliscott** [comment]
@alex-3sr that's me just shipped the v0.9.7 release now. Can you give it another shot?

**Comment by alex-3sr** [comment]
> @alex-3sr that's me just shipped the v0.9.7 release now. Can you give it another shot?

Correct, now the task is not stopping and continue, it's perfect ;)
```
  $ infracost breakdown --no-color --format json --path /home/vsts/work/1/s/Terraform --terraform-plan-flags "-var-file=/home/vsts/work/1/s/Terraform/Env/PROD.tf-variables.tfvars" --terraform-workspace PROD
time="2021-09-08T08:20:16Z" level=info msg="Detected Terraform directory at /home/vsts/work/1/s/Terraform"
time="2021-09-08T08:20:17Z" level=debug msg="Creating temporary config file for Terraform credentials"
time="2021-09-08T08:20:17Z" level=debug msg="TF_CLI_CONFIG_FILE is set, copying existing config from .terraformrc to config to temporary config file /tmp/595642170"
time="2021-09-08T08:20:17Z" level=warning msg="Unable to copy existing config from /home/vsts/work/1/s/Terraform/.terraformrc: open /home/vsts/work/1/s/Terraform/.terraformrc: no such file or directory"
time="2021-09-08T08:20:17Z" level=debug msg="Writing Terraform credentials to temporary config file /tmp/595642170"
etc...
```

Thank you thank you
Now I think I'm ready to generalize the devops template :) Need further check and some policy governance about branch policy, and I'll will be ok ;)

I think this one could be close, now all is working as expected ;)

Thank you again, and wish you both a good day
Regards,
Alex

**Comment by alikhajeh1** [comment]
Awesome - can this issue be closed?

**Comment by alex-3sr** [comment]
yes, of course, it was just perfect and appreciate your assistance.

Thanks and have a nice day
Alex
